apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-kyverno
  namespace: grafana
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "kyverno.itblast.ovh"
    http:
      paths:
      - pathType: Prefix
        path: "/login"
        backend:
          service:
            name: kyverno
            port:
              number: 80
