# permissions for end users to edit activemqartemissecurities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: activemqartemissecurity-editor-role
rules:
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemissecurities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemissecurities/status
  verbs:
  - get
