# permissions for end users to view activemqartemisaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: activemqartemisaddress-viewer-role
rules:
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisaddresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisaddresses/status
  verbs:
  - get
