# permissions for end users to view activemqartemisscaledowns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: activemqartemisscaledown-viewer-role
rules:
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisscaledowns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemisscaledowns/status
  verbs:
  - get
