global:
  #image:
  #  tag: "1.2.1"
  #  pullPolicy: IfNotPresent
  resources:
    requests:
      memory: '128Mi'
      cpu: '125m'
    limits:
      memory: '256Mi'
      cpu: '250m'
  metrics:
    enabled: true

  ingress:
    enabled: false

    ingressClassName: ""

    pathType: Prefix

    activeService: true
    hosts:
      - host: vault.itblast.ovh