{{- if and .Values.edgeNode.enabled (eq (include "seleniumGrid.useKEDA" .) "true") (eq .Values.autoscaling.scalingType "deployment") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-edge-scaledobject
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.autoscaling.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    deploymentName: {{ template "seleniumGrid.edgeNode.fullname" . }}
spec:
  maxReplicaCount: {{ .Values.edgeNode.maxReplicaCount }}
  scaleTargetRef:
    name: {{ template "seleniumGrid.edgeNode.fullname" . }}
  triggers:
    - type: selenium-grid
    {{- with .Values.edgeNode.hpa }}
      metadata: {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
{{- end }}
