apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-grafana
  namespace: keycloackx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "keycloackx.itblast.ovh"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: keycloackx-keycloakx-http
            port:
              number: 80
