apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- broker_activemqartemissecurity_crd.yaml
- broker_activemqartemisscaledown_crd.yaml
- broker_activemqartemis_crd.yaml
- broker_activemqartemisaddress_crd.yaml