
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-broker-amq-io-v1beta1-activemqartemis
  failurePolicy: Fail
  name: mactivemqartemis.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemises
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-broker-amq-io-v1beta1-activemqartemisaddress
  failurePolicy: Fail
  name: mactivemqartemisaddress.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemisaddresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-broker-amq-io-v1beta1-activemqartemissecurity
  failurePolicy: Fail
  name: mactivemqartemissecurity.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemissecurities
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-broker-amq-io-v1beta1-activemqartemis
  failurePolicy: Fail
  name: vactivemqartemis.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemises
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-broker-amq-io-v1beta1-activemqartemisaddress
  failurePolicy: Fail
  name: vactivemqartemisaddress.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemisaddresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-broker-amq-io-v1beta1-activemqartemissecurity
  failurePolicy: Fail
  name: vactivemqartemissecurity.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemissecurities
  sideEffects: None
