apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: activemq
  namespace: activemq-artemis-operator
  annotations:
    #kubernetes.io/ingress.class: nginx
    # type of authentication
    #nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    #nginx.ingress.kubernetes.io/auth-secret: artemis-console-d9fm75g829 
    # message to display with an appropriate context why the authentication is required
    #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - activemq.itblast.ovh
  rules:
    - host: activemq.itblast.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                #name: activemq-broker-hdls-svc
                name: activemq-service-global
                port:
                  #name: web
                  #number: 8161
                  number: 61616