apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  podMetricsEndpoints:
    - port: web
  namespaceSelector:
    matchNames:
      - monitoring