apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: activemq-broker
  namespace: activemq-artemis-operator
spec:
  
  console:
    expose: true
    sslEnabled: false
      #securityEnabled: true
      #adminUser: admin
      #adminPassword: admin

  adminUser: admin
  adminPassword: xxx
  connectors:
  - items:
    name: openwire
    host: 0.0.0.0
    port: 61616
  acceptors:
  - name: artemis
    bindToAllInterfaces: true
    port: 61616
    protocols: CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE
  env:
  #  - name: AMQ_ENABLE_JOLOKIA_AGENT
  #    value: true
    #AMQ_ENABLE_JOLOKIA_AGENT: true
  
    - name: JDK_JAVA_OPTIONS
      value: |
        -XshowSettings:system      
        -Dbrokerconfig.transaction-timeout=0 
        -Dbrokerconfig.globalMaxSize=1000000
        -Dbrokerconfig.security-enabled=true
        -Dhawtio.authenticationEnabled=true
      
  deploymentPlan:
    size: 1 #cluster mode deployment
    requireLogin: true
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.30.0
    persistenceEnabled: true 
    # DATA PERSISTENCE : ALL parameters required
    journalType: aio #nio
    messageMigration: true
    podSecurityContext:
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"
    storage:
      size: 2Gi
   
    #volumeMounts:
    #  - name: active-creds
    #    mountPath: /home/jboss/amq-broker/etc/jetty-realm.properties
    #    subPath: jetty-realm.properties
  #volumes:
  #- name: active-creds
  #  secret:
  #    secretName: creds
  #  extraMounts:
  #    secrets:
  #    - "basic-auth"
    