apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: activemq-broker
  namespace: activemq-artemis-operator
spec:
  
  console:
      expose: true
      sslEnabled: false
      #securityEnabled: true
      #adminUser: admin
      #adminPassword: admin

  adminUser: admin
  adminPassword: admin
  connectors:
  - items:
    name: openwire
    host: 0.0.0.0
    port: 61616
  acceptors:
  #  - name: amqp
  #    protocols: amqp
  #    port: 5672
  #    connectionsAllowed: 5
  - items:
      bindToAllInterfaces: true
      name: artemis
      port: 61616
      protocols: CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE
  #  - name: openwire
  #    expose: true
  #    protocols: OPENWIRE
  #    port: 61616
  #    connectionsAllowed: 1000
  env:
    - name: JDK_JAVA_OPTIONS
      value: |
        -XshowSettings:system      
        -Dbrokerconfig.transaction-timeout=0 
        -Dbrokerconfig.globalMaxSize=1000000
        -Dbrokerconfig.security-enabled=false
        -Dhawtio.authenticationEnabled=false
  deploymentPlan:
    size: 1 #cluster mode deployment
    #image: placeholder
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.30.0
    persistenceEnabled: true 
    # DATA PERSISTENCE : ALL parameters required
    journalType: aio #nio
    messageMigration: true
    podSecurityContext:
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"
    storage:
      size: 2Gi
    