apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#bases:
#- https://github.com/codefresh-contrib/kustomize-sample-app/tree/master/base
#- https://github.com/artemiscloud/activemq-artemis-operator/tree/main/config/certmanager
#- https://github.com/artemiscloud/activemq-artemis-operator/tree/main/config/crd/?ref=v1.0.15
#- https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/v1.0.15/deploy/operator.yaml
resources:
- namespace.yaml
- deploy
- activemq-artemis-broker.yaml
- ingress.yaml