apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: acticemq
  namespace: activemq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: acticemq
  podMetricsEndpoints:
    - port: web
  namespaceSelector:
    matchNames:
      - activemq