apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: activemq
  namespace: activemq-artemis-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: activemq
  podMetricsEndpoints:
    - port: web
  namespaceSelector:
    matchNames:
      - activemq