apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-vault
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "vault.itblast.ovh"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vault-internal
            port:
              number: 8200