apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-selenium
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "selenium.itblast.ovh2"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: selenium-selenium-hub
            port:
              number: 4444